### ISSUE TITLE
Package list not working

### ISSUE THREAD

**Issue by Lautaro-Cepeda** [slightc/pip-manager#12]
All options work except the list of packages. I can install packages without problems, etc.

![image](https://user-images.githubusercontent.com/102000800/159191625-c4c8c6fb-4e7c-4cd5-8693-0d0f1e7a0107.png)

**Comment by slightc** [comment]
can you show me your pip version by

```
pip -V
# or
pip3 -V
```

maybe you use an outdate version

waiting for your reply

**Comment by Lautaro-Cepeda** [comment]
![image](https://user-images.githubusercontent.com/102000800/159310940-0f741bac-88c9-402f-9017-f72cc33caf3b.png)

**Comment by lauiwi** [comment]
> can you show me your pip version by
> 
> ```
> pip -V
> # or
> pip3 -V
> ```
> 
> maybe you use an outdate version
> 
> waiting for your reply

**Comment by Lautaro-Cepeda** [comment]
Hey! managed to fix it! The solution was to uninstall python and delete all the folders that belonged to python (which are located in Appdata etc). Once it was uninstalled I went to the PATH and removed the environment variables pertaining to python. from there Install python again in a "custom" way so check the boxes to install it for all users so that there is no conflict with the directories and also check the box to add python to the PATH.

![image](https://user-images.githubusercontent.com/102000800/159537708-4009e88f-6260-469a-b8e1-07aa065514bd.png)

**Comment by leno4eks** [comment]
5. Очистить кеш VS Code
Закройте VS Code.

Удалите папку кеша:

Windows: %APPDATA%\Code\Cache

macOS/Linux: ~/.config/Code/Cache

Перезапустите VS Code.

 Мне помогло
