### ISSUE TITLE
issue: extension window just says "wait init ..."

### ISSUE THREAD

**Issue by emile-o** [slightc/pip-manager#13]
Extension unfortunately doesn't work for me. Window just says "wait init ..." the whole time.
If i click on any of the buttons they just say "command 'pip-manager.addPackage' not found" for instance

**Comment by mark-wehrmann** [comment]
I have the same. On VS Code installed on Chromebook (Debian 64-Bit)

pip3 -V     outputs
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)

pip    outputs
command not found

**Comment by slightc** [comment]
this extension depend extension ms-python.python, maybe you ms-python.python not actived,

you can try open a python file in vscode , you can see that select a version for your python in status bar like this.

<img width="387" alt="image" src="https://user-images.githubusercontent.com/17919546/159688711-fbd912bb-2d82-4f06-90a6-548efcc901a4.png">

then try open pip-manager again

**Comment by mark-wehrmann** [comment]
Works now without that I have changed anything. May a reboot has done some magic !?!?!

**Comment by mark-wehrmann** [comment]
Unfortunately it only worked on Windows installation not on Chrombook (Debain 64)

![image](https://user-images.githubusercontent.com/101988934/159764197-ee6bee60-0aed-47e3-93a3-3bb240fb647f.png)

As you can see: Python in Status Bar is visible
Also, other extensions such as Python Environment Manager work fine

**Comment by slightc** [comment]
<img width="942" alt="image" src="https://user-images.githubusercontent.com/17919546/159765841-424cf392-165f-4d6b-8fa2-61c761c63cbf.png">

can you check have any information in you output

**Comment by mark-wehrmann** [comment]
![image](https://user-images.githubusercontent.com/101988934/159790808-f643f7c5-0db6-438e-8707-a670ae346c3d.png)

See screenshot: Interestingly Pip Manager does not produce any output windows. Really weird. However those error messages are popping up instead. Any further idea?

**Comment by emile-o** [comment]
I also don't get Pip Manager output window
My OS is Ubuntu 21.10 with Snap version of VSCode

**Comment by calcuims** [comment]
I also get this issue. When I click any button it goes "Unexpected string in JSON at position 3" (sometimes position 0)

**Comment by thebrianlenz** [comment]
I am also experiencing this issue. I tried installing an earlier version (1.1.0), just out of curiosity, and it does seem to work.

**Comment by Phorensyk** [comment]
SOLUTION:

I'm using Ubuntu 22.04 LTS, python3.10, and have pip 22.0.4. I got the same 'wait init...' issue and even with ms-python.python active, couldn't get pip manager 1.1.1 to finish initializing. Similar to thebrianlenz, I switched to pip manager 1.1.0 and after reloading VS Code, got it working.

Hope this helps

**Comment by BobDenny** [comment]
Raspberry Pi Bulldog, same problem, never finishes init. VSCode and ms-python working OK. Backed down to 1.1.0, that version runs OK. **Thanks guys for that tip!** I have disabled sync for the extension because 1.1.1 runs fine on my Windows VSCode.

**Comment by slightc** [comment]
em，this is an annoying bug, I can't replicate the problem，that run fine in my windows macos and ubuntu, I will try fix it in 1.1.2. and welcome every guys PR to help me, thanks!

**Comment by emile-git** [comment]
When I downgraded to version 1.1.0 I got an "Unexpected token C in JSON at position 0" error. This might be related?

**Comment by BobDenny** [comment]
Hi well it is definitely within the changes between 1.1.0 and 1.1.1... you might do a diff-inspection to see what you changed, and you may find something surprising.

**Comment by darkvertex** [comment]
Hello, just here to say I also had the same issue. After installing 1.1.0 and making sure I had opened a Python file so the Python extension "woke up", it worked.

I'm in Ubuntu under WSL on Windows10.

**Comment by Julien-Quidam** [comment]
I have the same issue. When I try to refresh, I have this message : command 'pip-manager.refreshPackage' not found
In a shell : 
pip-manager.refreshPackage : pip-manager.refreshPackage: command not found

pip-manager : lunch pip-manager 1.0.4

I'm in Ubuntu, Python 3.10.4 and 3.7.13

**Comment by lz100** [comment]
same here `command 'pip-manager.refreshPackage' not found`, Ubuntu 20, python 3.8.10, pip manager 1.1.1

**Comment by BobDenny** [comment]
This is a very useful extension, I hope you  can fix 1.1.1. It is definitely in [this change set](https://github.com/slightc/pip-manager/commit/27d20256439e3dae3c6793d756ef775a936adedc) because 1.1.0 is fine.

**Comment by Elka2000** [comment]
@Phorensyk hi how are you installing the 1.0.0 version? I tried searching for it in the extensions tab but could not find it.

**Comment by Clysmo** [comment]
Found a solution here:
[https://github.com/slightc/pip-manager/issues/12]
It involves removing and reinstalling python installations!

**Comment by slightc** [comment]
new version released, that problem is resolved close this issue
[https://github.com/slightc/pip-manager/releases/tag/v1.1.2](v1.1.2)

**Comment by ghost** [comment]
If anyone is still looking - updating PIP  using 
python.exe -m pip install --upgrade pip

Fix it for me
