### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by BrunoSalgadoti** [slightc/pip-manager#14]
- Issue Type: `Performance`
- Extension Name: `pip-manager`
- Extension Version: `1.1.1`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.68.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/bruno/AppData/Local/Temp/slightc.pip-manager-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by slightc** [comment]
can you upload this cpuprofile?

**Comment by BrunoSalgadoti** [comment]
> unfortunately not from pip manager, the file was deleted, but I have other extensions that gave the same overload.

Infelizmente do pip manager não, o arquivo foi apagado, porém tenho de outras extensões que deram o mesma sobrecarga.

[zobo.php-intellisense-unresponsive.cpuprofile.txt](https://github.com/slightc/pip-manager/files/8960491/zobo.php-intellisense-unresponsive.cpuprofile.txt)
[ritwickdey.LiveServer-unresponsive.cpuprofile.txt](https://github.com/slightc/pip-manager/files/8960499/ritwickdey.LiveServer-unresponsive.cpuprofile.txt)

**Comment by slightc** [comment]
this is long not active, i will close this issue, thanks for your issue
