### ISSUE TITLE
Unexpected token <token > in JSON at position <position > and issue #13

### ISSUE THREAD

**Issue by Veerhan-glitch** [slightc/pip-manager#19]
while loading the extension, errors like:

Unexpected token . in JSON at position 4,

Unexpected token T in JSON at position 1, etc

keep popping up.

it is only showing (issue #13)
![image](https://user-images.githubusercontent.com/83816165/204222486-c5709415-6524-41e2-946f-3f48f319332c.png)

I have tried reinstalling but it did not work

**Comment by slightc** [comment]
can you test your pip/pip3 support output list with json format? please run cmd

``` bash
pip3 list --format json
# or
pip list --format json
```

**Comment by slightc** [comment]
you can watch this issue #20

**Comment by Veerhan-glitch** [comment]
yep got the problem, i forgot to check if pip was to the latest version. thanks for ur help!
