### ISSUE TITLE
1.77.0-insider work fail

### ISSUE THREAD

**Issue by heartacker** [slightc/pip-manager#23]
Get package failed, please run "pip list --format json" or "pip3 list --format json" check pip support json format

版本: 1.77.0-insider
提交: fa13bf16fd237afef07f4df0648da026f43e3963
日期: 2023-03-20T05:25:30.711Z
浏览器: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.77.0-insider Chrome/102.0.5005.196 Electron/19.1.11 Safari/537.36

**Comment by slightc** [comment]
what's your python version? maybe your python version to low

**Comment by slightc** [comment]
#20

**Comment by slightc** [comment]
#20

**Comment by coseto6125** [comment]
It's not python version too low, I use 3.11.3
I think the code parse json has bug.
when I check the extension log, the print pip json log has break line,
but same cmd in terminal is not like this, check below image.

Python 3.11.3
pip 23.1.2

![image](https://github.com/slightc/pip-manager/assets/80243681/d5a11f1a-e97e-47e5-992f-6fcebf332c0f)
<img width="1305" alt="image" src="https://github.com/slightc/pip-manager/assets/80243681/c2541dc0-3533-4677-b839-36d62c8d53fc">

**Comment by slightc** [comment]
fixed now
