### ISSUE TITLE
为什么一直显示“等待加载完成”？

### ISSUE THREAD

**Issue by stevezhengs** [slightc/pip-manager#27]
为什么一直显示“等待加载完成”？
![image](https://github.com/slightc/pip-manager/assets/11571926/8aba1491-20f7-4732-8893-d1fea7564e04)

**Comment by slightc** [comment]
I think that maybe a pip error, may your pip not support json format output

**Comment by slightc** [comment]
#18

**Comment by slightc** [comment]
that fixed now
