### ISSUE TITLE
search error message

### ISSUE THREAD

**Issue by cflin-cjcu** [slightc/pip-manager#4]
click 'search' icon, then show error message.

![image](https://user-images.githubusercontent.com/14834565/128619608-46beca96-f600-4e8a-bf3b-d5e73d25c757.png)

**Comment by slightc** [comment]
can you tell you vscode version， I‘m test in vscode 1.54.3, that is working

**Comment by slightc** [comment]
can you tell you vscode version， I‘m test in vscode 1.58.0, that is working

**Comment by cflin-cjcu** [comment]
> can you tell you vscode version， I‘m test in vscode 1.54.3, that is working

vscode newest version 1.59.0

**Comment by slightc** [comment]
Im test in 1.59.0 that also working，I will try to found this error, and can you provide to me more error information

**Comment by cflin-cjcu** [comment]
show installed packages is okay.   "Open in PyPI.." is okay
But add, remove, search package is show error messages.

![image](https://user-images.githubusercontent.com/14834565/128620399-29e2a6c3-f8f9-4064-9ef0-84666fb8331a.png)
![image](https://user-images.githubusercontent.com/14834565/128620514-676d7ca9-4b9b-4866-b907-8808d3c79cce.png)

**Comment by slightc** [comment]
You can try reinstall the extension  following the steps below.

1. Uninstall the extension
2. Close all VS Code instances
3. Reopen VS Code
4. Reinstall the extension

If still not working, I would ask you to check `Toggle Developer Tools / Console`, looking for error messages. Please also add your current OS.

Hope this helps

**Comment by cflin-cjcu** [comment]
Thanks for your kindly reply.
Following your suggest method, it still errors.
![image](https://user-images.githubusercontent.com/14834565/128621522-84ca6998-d624-4a74-895b-fd1d95ce5cca.png)

My OS is Win10.  
Maybe my vscode install too extensions to influence each other.
I will try another PC.  Thanks.

pip-manager is a good extension.

**Comment by cflin-cjcu** [comment]
I know  what's happen.
now I change my display  language  from 'en' to 'zh-cn'
It work..

![image](https://user-images.githubusercontent.com/14834565/128621874-55b540d4-2f47-4f52-a4e2-9f4e91618cb8.png)

**Comment by slightc** [comment]
oh, thanks, that hava some wrong for localize, i will fix in 1.0.13 as quickly

**Comment by slightc** [comment]
this error is fixed， you need update this exsitation to 1.0.13, hope you can use happy
