### ISSUE TITLE
[BUG] Unexpected token e in JSON at position 0

### ISSUE THREAD

**Issue by flight505** [slightc/pip-manager#7]
In some environments, I get the following error in VScode "Unexpected token e in JSON at position 0"
I am not sure which package is causing this, but the env from the requirements.txt should contain it. 

[requirements.txt](https://github.com/slightc/pip-manager/files/7026361/requirements.txt)

Thanks

**Comment by slightc** [comment]
maybe your pip not support output list with json format, you can test with

```
pip list --format json
# or
pip3 list --format json
```

I will done some work for this error

thank your comment

**Comment by slightc** [comment]
you can watch this issue #20
