### ISSUE TITLE
bug: Can't install requirements.txt on Windows

### ISSUE THREAD

**Issue by JanPokorny** [slightc/pip-manager#9]
When installing requirements.txt using the "Install python package from file" context menu entry, an extra slash is added to the beginning of path, making it invalid.

![obrazek](https://user-images.githubusercontent.com/4580066/136001174-0e55acb8-7e01-4b95-8982-121e7ca3962a.png)

**Comment by slightc** [comment]
thanks, I'm fixed this error and publish version 1.0.14
